name: Python Test

on:
  push:
    brances:
      - master


jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.8'


    - name: Install Pytest
      run: pip install pytest

    - name: Run Tests
      run: pytest
