name: Test Workflow

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Shell Script
      run: |
        echo "Github Actions test"
